# Use the latest Node.js base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which the server will run
EXPOSE 3001

# Define the command to start the server
CMD [ "npm", "start" ]
